# Generated by Django 5.2 on 2025-04-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_faculty_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_photos/'),
        ),
    ]
