# Generated by Django 5.2 on 2025-04-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_faculty_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='joining_date',
            field=models.DateField(null=True),
        ),
    ]
