# Generated by Django 5.2 on 2025-04-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_faculty_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='google_scholar_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
