# Generated by Django 4.2.20 on 2025-04-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_faculty_google_scholar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedemail',
            name='role',
            field=models.CharField(choices=[(3, 'Super Admin'), (2, 'Course Access'), (1, 'General User')], default=1, max_length=50),
        ),
    ]
