# Generated by Django 4.2.20 on 2025-04-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_allowedemail_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='last_name',
        ),
        migrations.AddField(
            model_name='faculty',
            name='full_name',
            field=models.CharField(default='Full Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='allowedemail',
            name='role',
            field=models.CharField(choices=[('3', 'Super Admin'), ('2', 'Course Access'), ('1', 'General User')], default=1, max_length=50),
        ),
    ]
