# Generated by Django 4.2.20 on 2025-04-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_remove_faculty_first_name_remove_faculty_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='full_name',
        ),
        migrations.AddField(
            model_name='faculty',
            name='name',
            field=models.CharField(default='Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('PROF', 'Professor'), ('ASSO_PROF', 'Associate Professor'), ('ASSI_PROF', 'Assistant Professor'), ('LECT', 'Lecturer'), ('TA', 'Teaching Assistant')], max_length=20, null=True),
        ),
    ]
