# Generated by Django 4.2.20 on 2025-04-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_remove_faculty_full_name_faculty_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Lecturer', 'Lecturer'), ('Teaching Assistant', 'Teaching Assistant')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaults/faculty.png', null=True, upload_to='faculty_photos/'),
        ),
    ]
