# Generated by Django 4.2.20 on 2025-04-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0009_alter_faculty_designation_alter_faculty_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='sl',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
