# Generated by Django 4.2.20 on 2025-04-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0010_faculty_sl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='sl',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('PROF', 'Professor'), ('ASSO_PROF', 'Associate Professor'), ('ASSI_PROF', 'Assistant Professor'), ('LECT', 'Lecturer'), ('TA', 'Teaching Assistant')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_photos/'),
        ),
    ]
