# Generated by Django 4.2.20 on 2025-04-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0011_remove_faculty_sl_alter_faculty_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='sl',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Lecturer', 'Lecturer'), ('Teaching Assistant', 'Teaching Assistant')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaults/faculty.png', null=True, upload_to='faculty_photos/'),
        ),
    ]
