# Generated by Django 5.2 on 2025-04-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0013_faculty_citation'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='orcid_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='researchgate_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='routine',
            field=models.FileField(blank=True, null=True, upload_to='faculty_routines/'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='scopus_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='shortname',
            field=models.CharField(default='N/A', max_length=5),
        ),
        migrations.AlterField(
            model_name='allowedemail',
            name='role',
            field=models.CharField(choices=[('5', 'Head'), ('4', 'Super Admin'), ('3', 'Course Access'), ('2', 'General User'), ('1', 'Club Member')], default=1, max_length=50),
        ),
    ]
