# Generated by Django 5.2 on 2025-04-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0015_alter_faculty_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholar_url', models.URLField(unique=True)),
                ('papers', models.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
