# Generated by Django 5.2 on 2025-05-01 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0016_scholarcache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='sl',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
