# Generated by Django 5.2 on 2025-05-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0017_alter_faculty_sl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='shortname',
            field=models.CharField(blank=True, default='N/A', max_length=5),
        ),
    ]
