# Generated by Django 4.2.20 on 2025-04-26 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculty', '0011_remove_faculty_sl_alter_faculty_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='club_logos/')),
                ('moto', models.CharField(max_length=255)),
                ('cover_picture', models.ImageField(upload_to='club_covers/')),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('convener', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='club_members/')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClubPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('post_type', models.CharField(choices=[('announcement', 'Announcement'), ('event', 'Event Details'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='club_posts/')),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='club_posts/')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='club_posts/')),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='club_posts/')),
                ('pic4', models.ImageField(blank=True, null=True, upload_to='club_posts/')),
                ('pic5', models.ImageField(blank=True, null=True, upload_to='club_posts/')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.clubmember')),
            ],
        ),
    ]
