# Generated by Django 4.2.20 on 2025-04-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='cover_picture',
            field=models.ImageField(default='defaults/clubcover.png', upload_to='club_covers/'),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(default='defaults/faculty.png', upload_to='club_logos/'),
        ),
    ]
