# Generated by Django 5.2 on 2025-04-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_club_cover_picture_alter_club_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(default='defaults/clubcover.png', upload_to='club_logos/'),
        ),
    ]
