# Generated by Django 5.2 on 2025-05-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_admissionresult_noticeboard_routine'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='academic_calendars/')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('credit', models.FloatField(default=0.0)),
                ('year', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=15, null=True)),
                ('semester', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd')], max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='curriculums/')),
            ],
        ),
        migrations.CreateModel(
            name='ExamRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='exam_routines/')),
            ],
        ),
        migrations.CreateModel(
            name='ICPCEventSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('paragraph', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='icpc_event_images/')),
                ('section_order', models.IntegerField()),
            ],
            options={
                'ordering': ['section_order'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='missions/')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='notices/')),
                ('description', models.TextField()),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='NoticeBoard',
        ),
        migrations.DeleteModel(
            name='PDFFile',
        ),
        migrations.AlterModelOptions(
            name='admissionresult',
            options={},
        ),
        migrations.RemoveField(
            model_name='admissionresult',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='admissionresult',
            name='result_type',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='routine_type',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='title',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='category',
            field=models.CharField(choices=[('written', 'Written Test'), ('final', 'Final Result'), ('waiting', 'Waiting List')], default='written', max_length=20),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='admission_results/images/'),
        ),
        migrations.AlterField(
            model_name='admissionresult',
            name='pdf_file',
            field=models.FileField(upload_to='admission_results/'),
        ),
        migrations.AlterField(
            model_name='admissionresult',
            name='upload_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='routine',
            name='semester',
            field=models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='routine',
            name='year',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], default='1', max_length=1),
        ),
    ]
